# -*- coding: utf-8 -*-
"""gruppo IV - tests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lcMbd3066c5tJieZLIiM7velP3yFtit
"""

import pandas as pd
from .transcoding.names.owid import col

covid_tests_url = (
    "https://raw.githubusercontent.com/owid/covid-19-data/master/"
    "public/data/testing/covid-testing-all-observations.csv"
)
col = col["owid"]


def parse_covid_tests():
    tests = pd.read_csv(covid_tests_url, parse_dates=["Date"]).rename(
        columns=col
    )

    tests["geo"] = ""
    tests["unit"] = ""
    tests.loc[:, ["geo", "unit"]] = (
        tests["entity"].str.split(" - ", 1, expand=True).values
    )

    tests = tests.drop(columns="entity")

    return tests
