# -*- coding: utf-8 -*-
"""gruppo IV - tests.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lcMbd3066c5tJieZLIiM7velP3yFtit
"""

import pandas as pd
from .transcoding.names.ecdc import col

covid_data_url = "https://opendata.ecdc.europa.eu""/covid19/casedistribution/csv"
col = col["ecdc"]

def parse_covid_world_data():
    ecdc = pd.read_csv(
        covid_data_url,
        parse_dates={"time": ["year", "month", "day"]},
        usecols=col.keys(),
    ).rename(columns=col)
    return ecdc
