lang = {
    "it": {
        "hospital_bed_tot": "Totale Posti Letto",
        "province": "Provincia",
        "region": "Regione",
        "population": "Popolazione",
        "death_rate_all_rel_freq": "Tasso di Mortalità Complessivo'",
        "age": "Eta'",
        "gender": "Genere",
        "year": "Anno",
        "discipline": "Disciplina",
        'latitude': "Latitudine",
        'longitude': "Longitudine",
    },
    "en": {
        "hospital_bed_tot": "Total Hospital Beds",
        "province": "Province",
        "region": "Region",
        "population": "Population",
        "death_rate_all_rel_freq": "Overall Death Rate'",
        "age": "Age",
        "gender": "Gender",
        "year": "Year",
        "discipline": "Discipline",
        'latitude': "Latitude",
        'longitude': "Longitude",
    },
}