lang = {
    "it": {
        "col": {
            "hospital_bed_tot": "Totale Posti Letto",
            "province": "Provincia",
            "region": "Regione",
            "population": "Popolazione",
            "death_rate_all_rel_freq": "Tasso di Mortalità Complessivo'",
            "age": "Eta'",
            "gender": "Genere",
            "year": "Anno",
            "discipline": "Disciplina",
            "latitude": "Latitudine",
            "longitude": "Longitudine",
            "NUTS": "Area Geografica",
            "time": "Data",
            "country": "Nazione",
            "n_hospitalized": "N. Ospedalizzati",
            "n_intensive_care": "N. Ricoverati in Terapia Intensiva",
            "tot_n_hospitalized": "Totale Ospedalizzati",
            "n_home_quarantine": "N. Casi in Autoquarantena",
            "n_active_cases": "N. Casi Attivi",
            "n_new_cases": "N. Nuovi Casi",
            "n_discharged_recovered": "N. Guariti",
            "n_deceased": "N. Deceduti",
            "tot_n_cases": "Totale Casi",
            "n_tested": "Totale Tamponi Effettuati",
            "epidemic_start": "Data di Inizio del Contagio",
            "epidemic_age": "N. Giorni Trascorsi dall'Inzio del Contagio",
        },
        "age": {
            "TOTAL": "total",
            "UNK": "unknown",
            "Y10-14": "10-14",
            "Y15-19": "15-19",
            "Y20-24": "20-24",
            "Y25-29": "25-29",
            "Y30-34": "30-34",
            "Y35-39": "35-39",
            "Y40-44": "40-44",
            "Y45-49": "45-49",
            "Y5-9": "5-9",
            "Y50-54": "50-54",
            "Y55-59": "55-59",
            "Y60-64": "60-64",
            "Y65-69": "65-69",
            "Y70-74": "70-74",
            "Y75-79": "75-79",
            "Y80-84": "80-84",
            "Y85-89": "85-89",
            "Y_GE85": "85+",
            "Y_GE90": "90+",
            "Y_LT5": "0-5",
        },
        "icd10": {
            "A-T_Z": "All causes of diseases (A00-Z99) excluding V00-Y98",
            "A-T_Z_XNB": "All causes of diseases (A00-Z99) excluding V00-Y98 and Z38",
            "A_B": "Certain infectious and parasitic diseases (A00-B99)",
            "A15-A19_B90": "Tuberculosis",
            "A00-A08": "Intestinal infectious diseases except diarrhoea",
            "A09": "Diarrhoea and gastroenteritis of presumed infectious origin",
            "A40_A41": "Septicaemia",
            "B20-B24": "Human immunodeficiency virus [HIV] disease",
            "A_B_OTH": "Other infectious and parasitic diseases (remainder of A00-B99)",
            "C00-D48": "Neoplasms",
            "C18-C21": "Malignant neoplasm of colon, rectosigmoid junction, rectum, anus and anal canal",
            "C33_C34": "Malignant neoplasm of trachea, bronchus and lung",
            "C43_C44": "Malignant neoplasms of skin",
            "C50": "Malignant neoplasm of breast",
            "C53-C55": "Malignant neoplasm of uterus",
            "C56": "Malignant neoplasm of ovary",
            "C61": "Malignant neoplasm of prostate",
            "C67": "Malignant neoplasm of bladder",
            "C_OTH": "Other malignant neoplasms (remainder of C00-C97)",
            "D00-D09": "In situ neoplasms",
            "D12": "Benign neoplasm of colon, rectum, anus and anal canal",
            "D25": "Leiomyoma of uterus",
            "D00-D48_OTH": "Other in situ neoplasms, benign neoplasms and neoplasms of uncertain or unknown behaviour (remainder of D00-D48)",
            "D50-D89": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism",
            "D50-D64": "Anaemias",
            "D65-D89": "Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism",
            "E": "Endocrine, nutritional and metabolic diseases (E00-E90)",
            "E10-E14": "Diabetes mellitus",
            "E_OTH": "Other endocrine, nutritional and metabolic diseases (remainder of E00-E90)",
            "F": "Mental and behavioural disorders (F00-F99)",
            "F00-F03": "Dementia",
            "F10": "Mental and behavioural disorders due to use of alcohol",
            "F11-F19": "Mental and behavioural disorders due to psychoactive substance use",
            "F20-F29": "Schizophrenia, schizotypal and delusional disorders",
            "F30-F39": "Mood [affective] disorders",
            "F_OTH": "Other mental and behavioural disorders (remainder of F00-F99)",
            "G": "Diseases of the nervous system (G00-G99)",
            "G30": "Alzheimer disease",
            "G35": "Multiple sclerosis",
            "G40_G41": "Epilepsy, status epilepticus",
            "G45": "Transient cerebral ischaemic attacks and related syndromes",
            "G_OTH": "Other diseases of the nervous system (remainder of G00-G99)",
            "H00-H59": "Diseases of the eye and adnexa",
            "H25_H26_H28": "Cataract",
            "H00-H59_OTH": "Other diseases of the eye and adnexa (remainder of H00-H59)",
            "H60-H95": "Diseases of the ear and mastoid process",
            "I": "Diseases of the circulatory system (I00-I99)",
            "I10-I15": "Hypertensive diseases",
            "I20": "Angina pectoris",
            "I21_I22": "Acute myocardial infarction including subsequent myocardial infarction",
            "I23-I25": "Other ischaemic heart disease",
            "I26-I28": "Pulmonary heart disease and diseases of pulmonary circulation",
            "I44-I49": "Conduction disorders and cardiac arrhythmias",
            "I50": "Heart failure",
            "I60-I69": "Cerebrovascular diseases",
            "I70": "Atherosclerosis",
            "I83": "Varicose veins of lower extremities",
            "I_OTH": "Other diseases of the circulatory system (remainder of I00-I99)",
            "J": "Diseases of the respiratory system (J00-J99)",
            "J00-J11": "Acute upper respiratory infections and influenza",
            "J12-J18": "Pneumonia",
            "J20-J22": "Other acute lower respiratory infections",
            "J35": "Chronic diseases of tonsils and adenoids",
            "UPRESPIR_OTH": "Other diseases of upper respiratory tract (J30-J34, J36-J39)",
            "J45_J46": "Asthma and status asthmaticus",
            "J40-J44_J47": "Other lower respiratory diseases",
            "J60-J99": "Other diseases of the respiratory system",
            "K": "Diseases of the digestive system (K00-K93)",
            "K00-K08": "Disorders of teeth and supporting structures",
            "K09-K14": "Other diseases of oral cavity, salivary glands and jaws",
            "K20-K23": "Diseases of oesophagus",
            "K25-K28": "Ulcer of stomach, duodenum and jejunum",
            "K29-K31": "Dyspepsia and other diseases of stomach and duodenum",
            "K35-K38": "Diseases of appendix",
            "K40": "Inguinal hernia",
            "K41-K46": "Other abdominal hernia",
            "K50_K51": "Crohn disease and ulcerative colitis",
            "K52": "Other noninfective gastroenteritis and colitis",
            "K56": "Paralytic ileus and intestinal obstruction without hernia",
            "K57": "Diverticular disease of intestine",
            "K60-K62": "Diseases of anus and rectum",
            "INTESTINE_OTH": "Other diseases of intestine (K55,K58-K59,K63)",
            "K70": "Alcoholic liver disease",
            "K71-K77": "Other diseases of liver",
            "K80": "Cholelithiasis",
            "K81-K83": "Other diseases of gallbladder and biliary tract",
            "K85-K87": "Diseases of pancreas",
            "K_OTH": "Other diseases of the digestive system (remainder of K00-K93)",
            "L": "Diseases of the skin and subcutaneous tissue (L00-L99)",
            "L00-L08": "Infections of the skin and subcutaneous tissue",
            "L20-L45": "Dermatitis, eczema and papulosquamous disorders",
            "L_OTH": "Other diseases of the skin and subcutaneous tissue (remainder of L00-L99)",
            "M": "Diseases of the musculoskeletal system and connective tissue (M00-M99)",
            "M16": "Coxarthrosis [arthrosis of hip]",
            "M17": "Gonarthrosis [arthrosis of knee]",
            "M23": "Internal derangement of knee",
            "ARTHROPAT_OTH": "Other arthropathies (M00-M15, M18-M22 ,M24-M25)",
            "M30-M36": "Systemic connective tissue disorders",
            "M40-M49": "Deforming dorsopathies and spondylopathies",
            "M50_M51": "Cervical disc disorders, other intervertebral disc disorders",
            "M54": "Dorsalgia",
            "M60-M79": "Soft tissue disorders",
            "M53_M80-M99": "Other disorders of the musculoskeletal system and connective tissue",
            "N": "Diseases of the genitourinary system (N00-N99)",
            "N00-N16": "Glomerular and renal tubulo-interstitial diseases",
            "N17-N19": "Renal failure",
            "N20-N23": "Urolithiasis",
            "N25-N39": "Other diseases of the urinary system",
            "N40": "Hyperplasia of prostate",
            "N41-N51": "Other diseases of male genital organs",
            "N60-N64": "Disorders of breast",
            "N70-N77": "Inflammatory diseases of female pelvic organs",
            "N91-N95": "Menstrual, menopausal and other female genital conditions",
            "N_OTH": "Other diseases of the genitourinary system (remainder of N00-N99)",
            "O": "Pregnancy, childbirth and the puerperium (O00-O99)",
            "O04": "Medical abortion",
            "ABORT_OTH": "Other pregnancy with abortive outcome (O00-O03,O05-O08)",
            "O10-O48": "Complications of pregnancy predominantly in the antenatal period",
            "O60-O75": "Complications of labour and delivery",
            "O80": "Single spontaneous delivery",
            "O81-O84": "Other delivery",
            "O85-O92": "Complications predominantly related to the puerperium",
            "O95-O99": "Other obstetric conditions",
            "P": "Certain conditions originating in the perinatal period (P00-P96)",
            "P07": "Disorders related to short gestation and low birth weight, not elsewhere classified",
            "P_OTH": "Other conditions originating in the perinatal period (remainder of P00-P96)",
            "Q": "Congenital malformations, deformations and chromosomal abnormalities (Q00-Q99)",
            "R": "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified (R00-R99)",
            "R07": "Pain in throat and chest",
            "R10": "Abdominal and pelvic pain",
            "R69": "Unknown and unspecified causes of morbidity",
            "R_OTH": "Other symptoms, signs and abnormal clinical and laboratory findings (remainder of R00-R99)",
            "S_T": "Injury, poisoning and certain other consequences of external causes (S00-T98)",
            "INJ_OTH": "Other injuries (S10-S51, S53-S71, S73-S81, S83-T14, T79)",
            "S06": "Intracranial injury",
            "INJ_HEAD_OTH": "Other injuries to the head (S00-S05, S07-S09)",
            "S52": "Fracture of forearm",
            "S72": "Fracture of femur",
            "S82": "Fracture of lower leg, including ankle",
            "T20-T32": "Burns and corrosions",
            "T36-T65": "Poisonings by drugs, medicaments and biological substances and toxic effects",
            "T80-T88": "Complications of surgical and medical care, not elsewhere classified",
            "T90-T98": "Sequelae of injuries, of poisoning and of other consequences of external causes",
            "S_T_OTH": "Other and unspecified effects of external causes (remainder of S00-T98)",
            "Z": "Factors influencing health status and contact with health services (Z00-Z99)",
            "Z03": "Medical observation and evaluation for suspected diseases and conditions",
            "Z30": "Contraceptive management",
            "Z38": "Liveborn infants according to place of birth",
            "Z51": "Other medical care",
            "Z_OTH": "Other factors influencing health status and contact with health services (remainder of Z00-Z99)",
        },
        "geo": {
            "EU27_2020": "European Union - 27 countries (from 2020)",
            "EU28": "European Union - 28 countries (2013-2020)",
            "EU27_2007": "European Union - 27 countries (2007-2013)",
            "BE": "Belgium",
            "BE1": "Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest",
            "BE10": "Région de Bruxelles-Capitale / Brussels Hoofdstedelijk Gewest",
            "BE2": "Vlaams Gewest",
            "BE21": "Prov. Antwerpen",
            "BE22": "Prov. Limburg (BE)",
            "BE23": "Prov. Oost-Vlaanderen",
            "BE24": "Prov. Vlaams-Brabant",
            "BE25": "Prov. West-Vlaanderen",
            "BE3": "Région wallonne",
            "BE31": "Prov. Brabant wallon",
            "BE32": "Prov. Hainaut",
            "BE33": "Prov. Liège",
            "BE34": "Prov. Luxembourg (BE)",
            "BE35": "Prov. Namur",
            "BG": "Bulgaria",
            "BG3": "Severna i yugoiztochna Bulgaria",
            "BG31": "Severozapaden",
            "BG32": "Severen tsentralen",
            "BG33": "Severoiztochen",
            "BG34": "Yugoiztochen",
            "BG4": "Yugozapadna i yuzhna tsentralna Bulgaria",
            "BG41": "Yugozapaden",
            "BG42": "Yuzhen tsentralen",
            "CZ": "Czechia",
            "CZ0": "Cesko",
            "CZ01": "Praha",
            "CZ02": "Strední Cechy",
            "CZ03": "Jihozápad",
            "CZ04": "Severozápad",
            "CZ05": "Severovýchod",
            "CZ06": "Jihovýchod",
            "CZ07": "Strední Morava",
            "CZ08": "Moravskoslezsko",
            "DK": "Denmark",
            "DK0": "Danmark",
            "DK01": "Hovedstaden",
            "DK02": "Sjælland",
            "DK03": "Syddanmark",
            "DK04": "Midtjylland",
            "DK05": "Nordjylland",
            "DE": "Germany (until 1990 former territory of the FRG)",
            "DE1": "Baden-Württemberg",
            "DE11": "Stuttgart",
            "DE12": "Karlsruhe",
            "DE13": "Freiburg",
            "DE14": "Tübingen",
            "DE2": "Bayern",
            "DE21": "Oberbayern",
            "DE22": "Niederbayern",
            "DE23": "Oberpfalz",
            "DE24": "Oberfranken",
            "DE25": "Mittelfranken",
            "DE26": "Unterfranken",
            "DE27": "Schwaben",
            "DE3": "Berlin",
            "DE30": "Berlin",
            "DE4": "Brandenburg",
            "DE40": "Brandenburg",
            "DE5": "Bremen",
            "DE50": "Bremen",
            "DE6": "Hamburg",
            "DE60": "Hamburg",
            "DE7": "Hessen",
            "DE71": "Darmstadt",
            "DE72": "Gießen",
            "DE73": "Kassel",
            "DE8": "Mecklenburg-Vorpommern",
            "DE80": "Mecklenburg-Vorpommern",
            "DE9": "Niedersachsen",
            "DE91": "Braunschweig",
            "DE92": "Hannover",
            "DE93": "Lüneburg",
            "DE94": "Weser-Ems",
            "DEA": "Nordrhein-Westfalen",
            "DEA1": "Düsseldorf",
            "DEA2": "Köln",
            "DEA3": "Münster",
            "DEA4": "Detmold",
            "DEA5": "Arnsberg",
            "DEB": "Rheinland-Pfalz",
            "DEB1": "Koblenz",
            "DEB2": "Trier",
            "DEB3": "Rheinhessen-Pfalz",
            "DEC": "Saarland",
            "DEC0": "Saarland",
            "DED": "Sachsen",
            "DED2": "Dresden",
            "DED4": "Chemnitz",
            "DED5": "Leipzig",
            "DEE": "Sachsen-Anhalt",
            "DEE0": "Sachsen-Anhalt",
            "DEF": "Schleswig-Holstein",
            "DEF0": "Schleswig-Holstein",
            "DEG": "Thüringen",
            "DEG0": "Thüringen",
            "EE": "Estonia",
            "EE0": "Eesti",
            "EE00": "Eesti",
            "IE": "Ireland",
            "IE0": "Éire/Ireland",
            "IE04": "Northern and Western",
            "IE05": "Southern",
            "IE06": "Eastern and Midland",
            "IE01": "Border, Midland and Western (NUTS 2013)",
            "IE02": "Southern and Eastern (NUTS 2013)",
            "EL": "Greece",
            "EL5": "Voreia Ellada",
            "EL51": "Anatoliki Makedonia, Thraki",
            "EL52": "Kentriki Makedonia",
            "EL53": "Dytiki Makedonia",
            "EL54": "Ipeiros",
            "EL6": "Kentriki Ellada",
            "EL61": "Thessalia",
            "EL62": "Ionia Nisia",
            "EL63": "Dytiki Ellada",
            "EL64": "Sterea Ellada",
            "EL65": "Peloponnisos",
            "EL3": "Attiki",
            "EL30": "Attiki",
            "EL4": "Nisia Aigaiou, Kriti",
            "EL41": "Voreio Aigaio",
            "EL42": "Notio Aigaio",
            "EL43": "Kriti",
            "ES": "Spain",
            "ES1": "Noroeste (ES)",
            "ES11": "Galicia",
            "ES12": "Principado de Asturias",
            "ES13": "Cantabria",
            "ES2": "Noreste (ES)",
            "ES21": "País Vasco",
            "ES22": "Comunidad Foral de Navarra",
            "ES23": "La Rioja",
            "ES24": "Aragón",
            "ES3": "Comunidad de Madrid",
            "ES30": "Comunidad de Madrid",
            "ES4": "Centro (ES)",
            "ES41": "Castilla y León",
            "ES42": "Castilla-la Mancha",
            "ES43": "Extremadura",
            "ES5": "Este (ES)",
            "ES51": "Cataluña",
            "ES52": "Comunidad Valenciana",
            "ES53": "Illes Balears",
            "ES6": "Sur (ES)",
            "ES61": "Andalucía",
            "ES62": "Región de Murcia",
            "ES63": "Ciudad Autónoma de Ceuta (ES)",
            "ES64": "Ciudad Autónoma de Melilla (ES)",
            "ES7": "Canarias (ES)",
            "ES70": "Canarias (ES)",
            "FR": "France",
            "FR1": "Île de France",
            "FR10": "Île de France",
            "FRB": "Centre - Val de Loire",
            "FRB0": "Centre - Val de Loire",
            "FRC": "Bourgogne - Franche-Comté",
            "FRC1": "Bourgogne",
            "FRC2": "Franche-Comté",
            "FRD": "Normandie",
            "FRD1": "Basse-Normandie",
            "FRD2": "Haute-Normandie",
            "FRE": "Nord-Pas-de-Calais - Picardie",
            "FRE1": "Nord-Pas-de-Calais",
            "FRE2": "Picardie",
            "FRF": "Alsace - Champagne-Ardenne - Lorraine",
            "FRF1": "Alsace",
            "FRF2": "Champagne-Ardenne",
            "FRF3": "Lorraine",
            "FRG": "Pays-de-la-Loire",
            "FRG0": "Pays-de-la-Loire",
            "FRH": "Bretagne",
            "FRH0": "Bretagne",
            "FRI": "Aquitaine - Limousin - Poitou-Charentes",
            "FRI1": "Aquitaine",
            "FRI2": "Limousin",
            "FRI3": "Poitou-Charentes",
            "FRJ": "Languedoc-Roussillon - Midi-Pyrénées",
            "FRJ1": "Languedoc-Roussillon",
            "FRJ2": "Midi-Pyrénées",
            "FRK": "Auvergne - Rhône-Alpes",
            "FRK1": "Auvergne",
            "FRK2": "Rhône-Alpes",
            "FRL": "Provence-Alpes-Côte d'Azur",
            "FRL0": "Provence-Alpes-Côte d'Azur",
            "FRM": "Corse",
            "FRM0": "Corse",
            "FRY": "RUP FR - Régions ultrapériphériques françaises",
            "FRY1": "Guadeloupe",
            "FRY2": "Martinique",
            "FRY3": "Guyane",
            "FRY4": "La Réunion",
            "FRY5": "Mayotte",
            "FR2": "Bassin Parisien (NUTS 2013)",
            "FR21": "Champagne-Ardenne (NUTS 2013)",
            "FR22": "Picardie (NUTS 2013)",
            "FR23": "Haute-Normandie (NUTS 2013)",
            "FR24": "Centre (FR) (NUTS 2013)",
            "FR25": "Basse-Normandie (NUTS 2013)",
            "FR26": "Bourgogne (NUTS 2013)",
            "FR3": "Nord-Pas-de-Calais (NUTS 2013)",
            "FR30": "Nord-Pas-de-Calais (NUTS 2013)",
            "FR4": "Est (FR) (NUTS 2013)",
            "FR41": "Lorraine (NUTS 2013)",
            "FR42": "Alsace (NUTS 2013)",
            "FR43": "Franche-Comté (NUTS 2013)",
            "FR5": "Ouest (FR) (NUTS 2013)",
            "FR51": "Pays de la Loire (NUTS 2013)",
            "FR52": "Bretagne (NUTS 2013)",
            "FR53": "Poitou-Charentes (NUTS 2013)",
            "FR6": "Sud-Ouest (FR) (NUTS 2013)",
            "FR61": "Aquitaine (NUTS 2013)",
            "FR62": "Midi-Pyrénées (NUTS 2013)",
            "FR63": "Limousin (NUTS 2013)",
            "FR7": "Centre-Est (FR) (NUTS 2013)",
            "FR71": "Rhône-Alpes (NUTS 2013)",
            "FR72": "Auvergne (NUTS 2013)",
            "FR8": "Méditerranée (NUTS 2013)",
            "FR81": "Languedoc-Roussillon (NUTS 2013)",
            "FR82": "Provence-Alpes-Côte d'Azur (NUTS 2013)",
            "FR83": "Corse (NUTS 2013)",
            "FRA": "Départements d'outre-mer (NUTS 2013)",
            "FRA1": "Guadeloupe (NUTS 2013)",
            "FRA2": "Martinique (NUTS 2013)",
            "FRA3": "Guyane (NUTS 2013)",
            "FRA4": "La Réunion (NUTS 2013)",
            "FRA5": "Mayotte (NUTS 2013)",
            "FRX": "Not regionalised / Unknown NUTS 1",
            "FRXX": "Not regionalised / Unknown NUTS 2",
            "HR": "Croatia",
            "HR0": "Hrvatska",
            "HR03": "Jadranska Hrvatska",
            "HR04": "Kontinentalna Hrvatska",
            "IT": "Italy",
            "ITC": "Nord-Ovest",
            "ITC1": "Piemonte",
            "ITC2": "Valle d'Aosta/Vallée d'Aoste",
            "ITC3": "Liguria",
            "ITC4": "Lombardia",
            "ITH": "Nord-Est",
            "ITH1": "Provincia Autonoma di Bolzano/Bozen",
            "ITH2": "Provincia Autonoma di Trento",
            "ITH3": "Veneto",
            "ITH4": "Friuli-Venezia Giulia",
            "ITH5": "Emilia-Romagna",
            "ITI": "Centro (IT)",
            "ITI1": "Toscana",
            "ITI2": "Umbria",
            "ITI3": "Marche",
            "ITI4": "Lazio",
            "ITF": "Sud",
            "ITF1": "Abruzzo",
            "ITF2": "Molise",
            "ITF3": "Campania",
            "ITF4": "Puglia",
            "ITF5": "Basilicata",
            "ITF6": "Calabria",
            "ITG": "Isole",
            "ITG1": "Sicilia",
            "ITG2": "Sardegna",
            "CY": "Cyprus",
            "CY0": "Kypros",
            "CY00": "Kypros",
            "LV": "Latvia",
            "LV0": "Latvija",
            "LV00": "Latvija",
            "LT": "Lithuania",
            "LT0": "Lietuva",
            "LT01": "Sostines regionas",
            "LT02": "Vidurio ir vakaru Lietuvos regionas",
            "LT00": "Lietuva (NUTS 2013)",
            "LU": "Luxembourg",
            "LU0": "Luxembourg",
            "LU00": "Luxembourg",
            "HU": "Hungary",
            "HU1": "Közép-Magyarország",
            "HU11": "Budapest",
            "HU12": "Pest",
            "HU10": "Közép-Magyarország (NUTS 2013)",
            "HU2": "Dunántúl",
            "HU21": "Közép-Dunántúl",
            "HU22": "Nyugat-Dunántúl",
            "HU23": "Dél-Dunántúl",
            "HU3": "Alföld és Észak",
            "HU31": "Észak-Magyarország",
            "HU32": "Észak-Alföld",
            "HU33": "Dél-Alföld",
            "HUX": "Not regionalised / Unknown NUTS 1",
            "HUXX": "Not regionalised / Unknown NUTS 2",
            "MT": "Malta",
            "MT0": "Malta",
            "MT00": "Malta",
            "NL": "Netherlands",
            "NL1": "Noord-Nederland",
            "NL11": "Groningen",
            "NL12": "Friesland (NL)",
            "NL13": "Drenthe",
            "NL2": "Oost-Nederland",
            "NL21": "Overijssel",
            "NL22": "Gelderland",
            "NL23": "Flevoland",
            "NL3": "West-Nederland",
            "NL31": "Utrecht",
            "NL32": "Noord-Holland",
            "NL33": "Zuid-Holland",
            "NL34": "Zeeland",
            "NL4": "Zuid-Nederland",
            "NL41": "Noord-Brabant",
            "NL42": "Limburg (NL)",
            "AT": "Austria",
            "AT1": "Ostösterreich",
            "AT11": "Burgenland (AT)",
            "AT12": "Niederösterreich",
            "AT13": "Wien",
            "AT2": "Südösterreich",
            "AT21": "Kärnten",
            "AT22": "Steiermark",
            "AT3": "Westösterreich",
            "AT31": "Oberösterreich",
            "AT32": "Salzburg",
            "AT33": "Tirol",
            "AT34": "Vorarlberg",
            "PL": "Poland",
            "PL1": "Region Centralny (NUTS 2013)",
            "PL11": "Lódzkie (NUTS 2013)",
            "PL12": "Mazowieckie (NUTS 2013)",
            "PL2": "Makroregion Poludniowy",
            "PL21": "Malopolskie",
            "PL22": "Slaskie",
            "PL3": "Region Wschodni (NUTS 2013)",
            "PL31": "Lubelskie (NUTS 2013)",
            "PL32": "Podkarpackie (NUTS 2013)",
            "PL33": "Swietokrzyskie (NUTS 2013)",
            "PL34": "Podlaskie (NUTS 2013)",
            "PL4": "Makroregion Pólnocno-Zachodni",
            "PL41": "Wielkopolskie",
            "PL42": "Zachodniopomorskie",
            "PL43": "Lubuskie",
            "PL5": "Makroregion Poludniowo-Zachodni",
            "PL51": "Dolnoslaskie",
            "PL52": "Opolskie",
            "PL6": "Makroregion Pólnocny",
            "PL61": "Kujawsko-Pomorskie",
            "PL62": "Warminsko-Mazurskie",
            "PL63": "Pomorskie",
            "PL7": "Makroregion Centralny",
            "PL71": "Lódzkie",
            "PL72": "Swietokrzyskie",
            "PL8": "Makroregion Wschodni",
            "PL81": "Lubelskie",
            "PL82": "Podkarpackie",
            "PL84": "Podlaskie",
            "PL9": "Makroregion Województwo Mazowieckie",
            "PL91": "Warszawski stoleczny",
            "PL92": "Mazowiecki regionalny",
            "PT": "Portugal",
            "PT1": "Continente",
            "PT11": "Norte",
            "PT15": "Algarve",
            "PT16": "Centro (PT)",
            "PT17": "Área Metropolitana de Lisboa",
            "PT18": "Alentejo",
            "PT2": "Região Autónoma dos Açores (PT)",
            "PT20": "Região Autónoma dos Açores (PT)",
            "PT3": "Região Autónoma da Madeira (PT)",
            "PT30": "Região Autónoma da Madeira (PT)",
            "RO": "Romania",
            "RO1": "Macroregiunea unu",
            "RO11": "Nord-Vest",
            "RO12": "Centru",
            "RO2": "Macroregiunea doi",
            "RO21": "Nord-Est",
            "RO22": "Sud-Est",
            "RO3": "Macroregiunea trei",
            "RO31": "Sud - Muntenia",
            "RO32": "Bucuresti - Ilfov",
            "RO4": "Macroregiunea patru",
            "RO41": "Sud-Vest Oltenia",
            "RO42": "Vest",
            "SI": "Slovenia",
            "SI0": "Slovenija",
            "SI03": "Vzhodna Slovenija",
            "SI04": "Zahodna Slovenija",
            "SK": "Slovakia",
            "SK0": "Slovensko",
            "SK01": "Bratislavský kraj",
            "SK02": "Západné Slovensko",
            "SK03": "Stredné Slovensko",
            "SK04": "Východné Slovensko",
            "FI": "Finland",
            "FI1": "Manner-Suomi",
            "FI19": "Länsi-Suomi",
            "FI1B": "Helsinki-Uusimaa",
            "FI1C": "Etelä-Suomi",
            "FI1D": "Pohjois- ja Itä-Suomi",
            "FI2": "Åland",
            "FI20": "Åland",
            "SE": "Sweden",
            "SE1": "Östra Sverige",
            "SE11": "Stockholm",
            "SE12": "Östra Mellansverige",
            "SE2": "Södra Sverige",
            "SE21": "Småland med öarna",
            "SE22": "Sydsverige",
            "SE23": "Västsverige",
            "SE3": "Norra Sverige",
            "SE31": "Norra Mellansverige",
            "SE32": "Mellersta Norrland",
            "SE33": "Övre Norrland",
            "UK": "United Kingdom",
            "UKC": "North East (UK)",
            "UKC1": "Tees Valley and Durham",
            "UKC2": "Northumberland and Tyne and Wear",
            "UKD": "North West (UK)",
            "UKD1": "Cumbria",
            "UKD3": "Greater Manchester",
            "UKD4": "Lancashire",
            "UKD6": "Cheshire",
            "UKD7": "Merseyside",
            "UKE": "Yorkshire and The Humber",
            "UKE1": "East Yorkshire and Northern Lincolnshire",
            "UKE2": "North Yorkshire",
            "UKE3": "South Yorkshire",
            "UKE4": "West Yorkshire",
            "UKF": "East Midlands (UK)",
            "UKF1": "Derbyshire and Nottinghamshire",
            "UKF2": "Leicestershire, Rutland and Northamptonshire",
            "UKF3": "Lincolnshire",
            "UKG": "West Midlands (UK)",
            "UKG1": "Herefordshire, Worcestershire and Warwickshire",
            "UKG2": "Shropshire and Staffordshire",
            "UKG3": "West Midlands",
            "UKH": "East of England",
            "UKH1": "East Anglia",
            "UKH2": "Bedfordshire and Hertfordshire",
            "UKH3": "Essex",
            "UKI": "London",
            "UKI3": "Inner London - West",
            "UKI4": "Inner London - East",
            "UKI5": "Outer London - East and North East",
            "UKI6": "Outer London - South",
            "UKI7": "Outer London - West and North West",
            "UKJ": "South East (UK)",
            "UKJ1": "Berkshire, Buckinghamshire and Oxfordshire",
            "UKJ2": "Surrey, East and West Sussex",
            "UKJ3": "Hampshire and Isle of Wight",
            "UKJ4": "Kent",
            "UKK": "South West (UK)",
            "UKK1": "Gloucestershire, Wiltshire and Bristol/Bath area",
            "UKK2": "Dorset and Somerset",
            "UKK3": "Cornwall and Isles of Scilly",
            "UKK4": "Devon",
            "UKL": "Wales",
            "UKL1": "West Wales and The Valleys",
            "UKL2": "East Wales",
            "UKM": "Scotland",
            "UKM2": "Eastern Scotland (NUTS 2013)",
            "UKM3": "South Western Scotland (NUTS 2013)",
            "UKM5": "North Eastern Scotland",
            "UKM6": "Highlands and Islands",
            "UKM7": "Eastern Scotland",
            "UKM8": "West Central Scotland",
            "UKM9": "Southern Scotland",
            "UKN": "Northern Ireland (UK)",
            "UKN0": "Northern Ireland (UK)",
            "EFTA": "European Free Trade Association",
            "IS": "Iceland",
            "IS0": "Ísland",
            "IS00": "Ísland",
            "LI": "Liechtenstein",
            "LI0": "Liechtenstein",
            "LI00": "Liechtenstein",
            "NO": "Norway",
            "NO0": "Norge",
            "NO01": "Oslo og Akershus",
            "NO02": "Hedmark og Oppland",
            "NO03": "Sør-Østlandet",
            "NO04": "Agder og Rogaland",
            "NO05": "Vestlandet",
            "NO06": "Trøndelag",
            "NO07": "Nord-Norge",
            "CH": "Switzerland",
            "CH0": "Schweiz/Suisse/Svizzera",
            "CH01": "Région lémanique",
            "CH02": "Espace Mittelland",
            "CH03": "Nordwestschweiz",
            "CH04": "Zürich",
            "CH05": "Ostschweiz",
            "CH06": "Zentralschweiz",
            "CH07": "Ticino",
            "ME": "Montenegro",
            "ME0": "Crna Gora",
            "ME00": "Crna Gora",
            "MK": "North Macedonia",
            "MK0": "Severna Makedonija",
            "MK00": "Severna Makedonija",
            "MKX": "Not regionalised / Unknown level 1",
            "MKXX": "Not regionalised / Unknown level 2",
            "AL": "Albania",
            "AL0": "Shqipëria",
            "AL01": "Veri",
            "AL02": "Qender",
            "AL03": "Jug",
            "ALX": "Not regionalised / Unknown level 1",
            "ALXX": "Not regionalised / Unknown level 2",
            "RS": "Serbia",
            "RS1": "Srbija - sever",
            "RS11": "Beogradski region",
            "RS12": "Region Vojvodine",
            "RS2": "Srbija - jug",
            "RS21": "Region Sumadije i Zapadne Srbije",
            "RS22": "Region Juzne i Istocne Srbije",
            "TR": "Turkey",
            "TR1": "Istanbul",
            "TR10": "Istanbul",
            "TR2": "Bati Marmara",
            "TR21": "Tekirdag, Edirne, Kirklareli",
            "TR22": "Balikesir, Çanakkale",
            "TR3": "Ege",
            "TR31": "Izmir",
            "TR32": "Aydin, Denizli, Mugla",
            "TR33": "Manisa, Afyonkarahisar, Kütahya, Usak",
            "TR4": "Dogu Marmara",
            "TR41": "Bursa, Eskisehir, Bilecik",
            "TR42": "Kocaeli, Sakarya, Düzce, Bolu, Yalova",
            "TR5": "Bati Anadolu",
            "TR51": "Ankara",
            "TR52": "Konya, Karaman",
            "TR6": "Akdeniz",
            "TR61": "Antalya, Isparta, Burdur",
            "TR62": "Adana, Mersin",
            "TR63": "Hatay, Kahramanmaras, Osmaniye",
            "TR7": "Orta Anadolu",
            "TR71": "Kirikkale, Aksaray, Nigde, Nevsehir, Kirsehir",
            "TR72": "Kayseri, Sivas, Yozgat",
            "TR8": "Bati Karadeniz",
            "TR81": "Zonguldak, Karabük, Bartin",
            "TR82": "Kastamonu, Çankiri, Sinop",
            "TR83": "Samsun, Tokat, Çorum, Amasya",
            "TR9": "Dogu Karadeniz",
            "TR90": "Trabzon, Ordu, Giresun, Rize, Artvin, Gümüshane",
            "TRA": "Kuzeydogu Anadolu",
            "TRA1": "Erzurum, Erzincan, Bayburt",
            "TRA2": "Agri, Kars, Igdir, Ardahan",
            "TRB": "Ortadogu Anadolu",
            "TRB1": "Malatya, Elazig, Bingöl, Tunceli",
            "TRB2": "Van, Mus, Bitlis, Hakkari",
            "TRC": "Güneydogu Anadolu",
            "TRC1": "Gaziantep, Adiyaman, Kilis",
            "TRC2": "Sanliurfa, Diyarbakir",
            "TRC3": "Mardin, Batman, Sirnak, Siirt",
        }
    },
    "en": {
        "col": {
            "hospital_bed_tot": "Total Hospital Beds",
            "province": "Province",
            "region": "Region",
            "population": "Population",
            "death_rate_all_rel_freq": "Overall Death Rate'",
            "age": "Age",
            "gender": "Gender",
            "year": "Year",
            "discipline": "Discipline",
            "latitude": "Latitude",
            "longitude": "Longitude",
        },
    },
}
