col = {
    "dpc-province": {
        # dpc province
        "codice_provincia": "province_code",
        "codice_regione": "region_code",
        "data": "time",
        "denominazione_provincia": "province",
        "denominazione_regione": "region",
        "lat": "latitude",
        "long": "longitude",
        "sigla_provincia": "province_short",
        "stato": "country",
        "totale_casi": "tot_n_cases",
    },
    "dpc-regions": {
        # dpc regions
        "codice_provincia": "province_code",
        "codice_regione": "region_code",
        "data": "time",
        "deceduti": "n_deceased",
        "denominazione_provincia": "province",
        "denominazione_regione": "region",
        "dimessi_guariti": "n_discharged_recovered",
        "lat": "latitude",
        "long": "longitude",
        "isolamento_domiciliare": "n_home_quarantine",
        "nuovi_attualmente_positivi": "n_new_cases",
        "ricoverati_con_sintomi": "n_hospitalized",
        "sigla_provincia": "province_short",
        "stato": "country",
        "tamponi": "n_tested",
        "totale_attualmente_positivi": "n_active_cases",
        "totale_casi": "tot_n_cases",
        "terapia_intensiva": "n_intensive_care",
        "totale_ospedalizzati": "tot_n_hospitalized",
    },
    "hospital_beds_by_discipline_hospital": {
        # salute.gov.it/dataset_96 hospital_beds_by_discipline_hospital
        "Anno": "time",
        "Codice Regione": "region_code",
        "Descrizione Regione": "region",
        "Codice Azienda": "asl_code",
        "Tipo Azienda": "asl_type",
        "Codice struttura": "hospital_id",
        "Subcodice": "subcode",
        "Denominazione Struttura/Stabilimento": "hospital_name",
        "Indirizzo": "address",
        "Codice Comune": "zip_code",
        "Comune": "municipality",
        "Sigla Provincia": "province_short",
        "Codice tipo struttura": "hospital_type_id",
        "Descrizione tipo struttura": "hospital_type",
        "Codice disciplina": "discipline_id",
        "Descrizione disciplina": "discipline",
        "Tipo di Disciplina": "discipline_type",
        "N° Reparti": "n_wards",
        "Posti letto degenza ordinaria": "n_hosp_bed_ordinary",
        "Posti letto degenza a pagamento": "n_hosp_bed_paid",
        "Posti letto Day Hospital": "n_hospital_bed_dayhospital",
        "Posti letto Day Surgery": "n_hospital_bed_daysurgery",
        "Totale posti letto": "tot_n_hospital_bed",
    },
    "salutegov-2": {
        # salute.gov.it/dataset_96 posti letto disciplina
        "ANNO": "time",
        "CODICE REGIONE": "region_code",
        "DENOMINAZIONE REGIONE": "region",
        "CODICE AZIENDA": "asl_code",
        "DENOMINAZIONE AZIENDA": "asl_name",
        "INDIRIZZO": "address",
        "CAP": "zip_code",
        "COMUNE": "municipality",
        "SIGLA PROVINCIA": "province_short",
        "TELEFONO": "phone",
        "FAX": "fax",
        "E-MAIL": "email",
        "SITO WEB": "website",
        "PARTITA IVA": "vat",
    },
    "istat": {
        # Istat population by province, gender, age
        "ITTER107": "geo",
        "ETA1": "age_id",
        "STATCIV2": "marital_status_id",
        "SEXISTAT1": "gender_id",
        "Territory": "geo_name",
        "Data type": "data_type",
        "Gender": "gender",
        "Age": "age",
        "Marital status": "marital_status",
        "Value": "value",
        "Regione": "region",
        "Provincia": "province",
        "Età": "age",
        "Totale Maschi": "male",
        "Totale Femmine": "female",
        "TIME": "time",
        "Underlying cause of death - European Short List": "cause_of_death",
        "REG": "region_code",
        "PROV": "province_code",
        "NOME_REGIONE": "region",
        "NOME_PROVINCIA": "province",
        "NOME_COMUNE": "municipality",
        "COD_PROVCOM": "prov_town_code",
        "CL_ETA": "age",
    },
}


var = {
    "istat": [
        # ("geo_name", "Valle d'Aosta / Vallée d'Aoste", "Aosta"),
        # ("geo", "ITC20", "Aosta"),
        ("geo_name", "Bolzano / Bozen", "Bolzano"),
        ("geo_name", "Massa-Carrara", "Massa Carrara"),
        ("genders", "males", "male"),
        ("genders", "females", "female"),
        ("age", "[A-z ]+", ""),
    ]
}
