human_names = {
    "it": {
        "hospital_bed_tot": "Totale Posti Letto",
        "province": "Provincia",
        "region": "Regione",
        "population": "Popolazione",
        "death_rate_all_rel_freq": "Tasso di Mortalità Complessivo'",
        "age": "Eta'",
        "gender": "Genere",
        "year": "Anno",
        "discipline": "Disciplina",
        'latitude': "Latitudine",
        'longitude': "Longitudine",
    },
    "en": {
        "hospital_bed_tot": "Total Hospital Beds",
        "province": "Province",
        "region": "Region",
        "population": "Population",
        "death_rate_all_rel_freq": "Overall Death Rate'",
        "age": "Age",
        "gender": "Gender",
        "year": "Year",
        "discipline": "Discipline",
        'latitude': "Latitude",
        'longitude': "Longitude",
    },
}

col_names = {

    # dpc province
    'codice_provincia': 'province_code',
    'codice_regione': 'region_code',
    'data': 'date',
    'denominazione_provincia': 'province',
    'denominazione_regione': 'region',
    'lat': 'latitude',
    'long': 'longitude',
    'sigla_provincia': 'province_short',
    'stato': 'country',
    'totale_casi': 'tot_n_cases',

    # dpc regioni
    'deceduti': 'n_deceased',
    'dimessi_guariti': 'n_discharged_recovered',
    'isolamento_domiciliare': 'n_home_quarantine',
    'nuovi_attualmente_positivi': 'n_new_cases',
    'ricoverati_con_sintomi': 'n_hospitalized',
    'tamponi': 'n_tested',
    'terapia_intensiva': 'n_intensive_care',
    'totale_attualmente_positivi': 'n_active_cases',
    'totale_ospedalizzati': 'tot_n_hospitalized',

    # worldometers covid deepdive age
    "AGE": "age",
    "SEX": "gender",
    "PRE-EXISTING CONDITION": "pre_medical_condition",
    "DEATH RATE confirmed cases": "death_rate_confirmed_rel_freq",
    "DEATH RATE all cases": "death_rate_all_rel_freq",

    # salute.gov.it/dataset_96 posti letto disciplina
    "Anno": "year",
    "Codice Regione": "region_code",
    "Descrizione Regione": "region",
    "Codice Azienda": "asl_code",
    "Tipo Azienda": "asl_type",
    "Codice struttura": "hospital_id",
    "Subcodice": "subcode",
    "Denominazione Struttura/Stabilimento": "hospital_name",
    "Indirizzo": "address",
    "Codice Comune": "zip_code",
    "Comune": "town",
    "Sigla Provincia": "province_short",
    "Codice tipo struttura": "hospital_type_id",
    "Descrizione tipo struttura": "hospital_type",
    "Codice disciplina": "discipline_id",
    "Descrizione disciplina": "discipline",
    "Tipo di Disciplina": "discipline_type",
    "N° Reparti": "n_wards",
    "Posti letto degenza ordinaria": "n_hosp_bed_ordinary",
    "Posti letto degenza a pagamento": "n_hosp_bed_paid",
    "Posti letto Day Hospital": "n_hospital_bed_dayhospital",
    "Posti letto Day Surgery": "n_hospital_bed_daysurgery",
    "Totale posti letto": "tot_n_hospital_bed",

    # salute.gov.it/dataset_96 posti letto disciplina
    'ANNO': "year",
    'CODICE REGIONE': "region_code",
    'DENOMINAZIONE REGIONE': "region",
    'CODICE AZIENDA': "asl_code",
    'DENOMINAZIONE AZIENDA': "asl_name",
    'INDIRIZZO': "address",
    'CAP': "zip_code",
    'COMUNE': "town",
    'SIGLA PROVINCIA': "province_short",
    'TELEFONO': "phone",
    'FAX': "fax",
    'E-MAIL': "email",
    'SITO WEB': "website",
    'PARTITA IVA': "vat",

    # Istat population by province, gender, age
    "Territory": "province",
    "Gender": "gender",
    "Age": "age",
    "Marital status": "marital_status",
    "Value": "population",

}
