{
    # POPULATION
    "demo_r_d2jan": "Population on 1 January by age, sex and NUTS 2 region",
    "demo_r_pjangrp3": "Population on 1 January by age group, sex and NUTS 3 region",
    "demo_r_d3dens": "Population density by NUTS 3 region",

    # HEALTH CARE EXPENDITURE
    "hlth_sha11_hp": "Health care expenditure by provider",
    "hlth_sha11_hc": "Health care expenditure by function",
    "hlth_sha11_hf": "Health care expenditure by financing scheme",
    "hlth_sha11_hchp": "Expenditure for selected health care functions by health care providers",
    "hlth_sha11_hchf": "Expenditure for selected health care functions by health care financing schemes",
    "hlth_sha11_hphf": "Expenditure for selected health care providers by health care financing schemes",

    # HEALTH CARE PERSONNEL
    "hlth_rs_prshp1": "Health personnel employed in hospital",
    "hlth_rs_prsns": "Nursing and caring professionals",
    "hlth_rs_spec": "Physicians by medical speciality",
    "hlth_rs_phys": "Physicians by sex and age",
    "hlth_rs_prsrg": "Health personnel by NUTS 2 regions",
    "hlth_rs_grd": "Health graduates",
    "hlth_rs_prs1": "Health personnel (excluding nursing and caring professionals)",
    "hlth_rs_wkmg": "Health workforce migration",

    # HEALTH CARE CAPACITY
    "hlth_rs_bds": "Hospital beds by type of care",
    "hlth_rs_bds2": "Hospital beds by hospital ownership",
    "hlth_rs_bdsrg": "Hospital beds by NUTS 2 regions",
    "hlth_rs_bdsns": "Long-term care beds in nursing and residential care facilities by NUTS 2 regions",
    "hlth_rs_tech": "Technical resources in hospital",
    "hlth_rs_equip": "Medical technology",

    # HOSPITALIZATION AND DIAGNOSES
    "hlth_co_dischls": "Hospital discharges and length of stay for inpatient and curative care",
    "hlth_co_bedoc": "Curative care bed occupancy rate",
    "hlth_co_dischnr": "Non-residents among all hospital discharges, %",
    "hlth_ehis_ho1e": "Self-reported hospital in-patient and day-patient admissions by sex, age and educational attainment level",
    "hlth_ehis_ho1u": "Self-reported hospital in-patient and day-patient admissions by sex, age and degree of urbanisation",
    "hlth_co_disch1": "Hospital discharges by diagnosis, in-patients, total number",
    "hlth_co_disch2": "Hospital discharges by diagnosis, in-patients, per 100 000 inhabitants",
    "hlth_co_disch3": "Hospital discharges by diagnosis, day cases, total number",
    "hlth_co_disch4": "Hospital discharges by diagnosis, day cases, per 100 000 inhabitants",
    "hlth_ehis_hc8": "Self-reported hospital in-patient and day-patient admissions by sex, age and educational attainment level (%)",
    "hlth_co_disch1t": "Hospital discharges by diagnosis and NUTS 2 regions, in-patients, total number - total",
    "hlth_co_disch1m": "Hospital discharges by diagnosis and NUTS 2 regions, in-patients, total number - males",
    "hlth_co_disch1f": "Hospital discharges by diagnosis, NUTS 2 regions, in-patients and total number - females",
    "hlth_co_disch2t": "Hospital discharges by diagnosis and NUTS 2 regions, in-patients, per 100 000 inhabitants - total",
    "hlth_co_disch2m": "Hospital discharges by diagnosis and NUTS 2 regions, in-patients, per 100 000 inhabitants - males",
    "hlth_co_disch2f": "Hospital discharges by diagnosis and NUTS 2 regions, in-patients, per 100 000 inhabitants - females",
    "hlth_co_disch3t": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, total number - total",
    "hlth_co_disch3m": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, total number - males",
    "hlth_co_disch3f": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, total number - females",
    "hlth_co_disch4t": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, per 100 000 inhabitants - total",
    "hlth_co_disch4m": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, per 100 000 inhabitants - males",
    "hlth_co_disch4f": "Hospital discharges by diagnosis and NUTS 2 regions, day cases, per 100 000 inhabitants - females",
    "hlth_co_inpst": "In-patient average length of stay (days)",
    "hlth_co_inpstt": "In-patient average length of stay (days) by NUTS 2 regions - total",
    "hlth_co_inpstm": "In-patient average length of stay (days) by NUTS 2 regions - males",
    "hlth_co_inpstf": "In-patient average length of stay (days) by NUTS 2 regions - females",
    "hlth_co_hosday": "Hospital days of in-patients",
    "hlth_co_hosdayt": "Hospital days of in-patients by NUTS 2 regions - total",
    "hlth_co_hosdaym": "Hospital days of in-patients by NUTS 2 regions - males",
    "hlth_co_hosdayf": "Hospital days of in-patients by NUTS 2 regions - females",
    "hlth_co_proc2": "Surgical operations and procedures performed in hospitals by ICD-9-CM",
    "hlth_co_exam": "Medical technologies - examinations by medical imaging techniques (CT, MRI and PET)",
    "hlth_co_ren": "End-stage renal failure (ESRF) patients",

    # MEDICAL CONSULTATIONS
    "hlth_ehis_am1e": "Self-reported time elapsed since last visit to a medical professional by sex, age and educational attainment level",
    "hlth_ehis_am2u": "Self-reported consultations of a medical professional by sex, age and degree of urbanisation",
    "hlth_ehis_am1u": "Self-reported time elapsed since last visit to a medical professional by sex, age and degree of urbanisation",
    "hlth_ehis_am2e": "Self-reported consultations of a medical professional by sex, age and educational attainment level",
    "hlth_ehis_am6e": "Self-reported consultation of mental healthcare or rehabilitative care professionals by sex, age and educational attainment level",
    "hlth_ehis_am6u": "Self-reported consultation of mental healthcare or rehabilitative care professionals by sex, age and degree of urbanisation",
    "hlth_hc_phys": "Consultation of a medical doctor (in private practice or as outpatient) per inhabitant",
    "hlth_hc_dent": "Consultation of a dentist per inhabitant",
    "hlth_ehis_am2b": "Self-reported consultations of a medical professional by sex, age and country of birth",
    "hlth_ehis_am2c": "Self-reported consultations of a medical professional by sex, age and country of citizenship",
    "hlth_ehis_am2d": "Self-reported consultations of a medical professional by sex, age and level of activity limitation",
    "hlth_ehis_am6d": "Self-reported consultation of mental healthcare or rehabilitative care professionals by sex, age and level of activity limitation",
    "hlth_ehis_hc5": "Self-reported consultation of a medical professional by sex, age and educational attainment level (%)",
    "hlth_ehis_hc6": "Self-reported consultation of a psychologist or physiotherapist by sex, age and educational attainment level (%)",
}